export const ACTIONS = {
    GET_BOOK_RESPONSE: "GET_BOOK_RESPONSE",
    NEW_BOOK: "NEW_BOOK",
    GET_BOOK_REQUESTED: "GET_BOOK_REQUESTED",
    BOOKS_MODIFIED: "BOOKS_MODIFIED",
    SEARCH_BAR_TEXT: "SEARCH_BAR_TEXT"
};
